# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - master
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: S3 Test
      env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
      run: |
            aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://git-repo-action-test


